SubsidizedDutyMeal/Models/View_Model/MealScheduleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SubsidizedDutyMeal.Models.View_Model
{
    public class MealScheduleViewModel
    {
        public int ID { get; set; }
        public DateTime Date { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string OrderType { get; set; }
        public string MealName { get; set; }
        public string MealType { get; set; }
        public string Position { get; set; }
        public string Status { get; set; }
        public string Details { get; set; }

    }
}

SubsidizedDutyMeal/Controllers/MealScheduleController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Linq.Dynamic;
using System.Web;
using System.Web.Mvc;
using SubsidizedDutyMeal.DAL;
using SubsidizedDutyMeal.Models;
using SubsidizedDutyMeal.Models.View_Model;

namespace SubsidizedDutyMeal.Controllers
{
    public class MealScheduleController : Controller
    {
        private SDMContext db = new SDMContext();
        // GET: MealSchedule
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult getData(int draw, int start, int length, string strcode, string domain, int noCols, DateTime? dt)
        {
            var sortColumn = Request["order[0][column]"];
            var sortColumnDir = Request["order[0][dir]"];
            var searchValue = Request["search[value]"];
            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;
            int recordsFiltered = 0;
            int recordsTotal = 0;

        

            var v = db.OrderHeaders
                    .Where(b => b.Status != "Deleted")
                    //.Where(b => b.Status == "Active")
                    .Where(b => b.Date == dt)
                    .Select(b =>
                            new MealScheduleViewModel()
                            {

                               ID = b.ID,
                               Date = b.Date,
                               EmployeeID = b.EmployeeID,
                               EmployeeName = db.Employees.Where(c => c.EmployeeID == b.EmployeeID).Select(c => c.LastName + ", " + c.FirstName).FirstOrDefault(),
                               Status  = b.Status
                            }
                    );





            recordsTotal = v.Count();

           
            DateTime dval = new DateTime();
            Boolean hasDateCreated = false;
            string strFilter = "";
            for (int i = 0; i < noCols; i++)
            {
                string colval = Request["columns[" + i + "][search][value]"];
                if (colval != "")
                {
                    string colSearch = Request["columns[" + i + "][data]"];


                    if (colSearch == "Date")
                    {
                        dval = DateTime.Parse(colval);
                        hasDateCreated = true;
                    }
                    else
                    {
                        if (strFilter == "")
                        {
                            if (colval == "*")
                            {
                                strFilter = "(" + colSearch + " != " + "" + ")";
                            }
                            else
                            {
                                strFilter = colSearch + ".Contains(" + "\"" + colval + "\"" + ")";
                            }
                        }
                        else
                        {
                            strFilter = strFilter + " && " + colSearch + ".Contains(" + "\"" + colval + "\"" + ")";
                        }
                    }
                    if (strFilter != "")
                    {
                        v = v.Where(strFilter);
                    }
                }
            }

            if (hasDateCreated)
            {
                v = v.Where("Date = @0", dval);
            }

            recordsFiltered = v.Count();





            if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
            {
                string col = Request["columns[" + sortColumn + "][data]"];
                v = v.OrderBy(col + " " + sortColumnDir);
            }

            var x = v.ToList();
            if (pageSize < 0)
            {
                pageSize = recordsFiltered;
            }
            var lstData = v.Skip(skip).Take(pageSize).ToList();



            var model = new
            {
                draw = draw,
                recordsFiltered = recordsFiltered,
                recordsTotal = recordsTotal,
                data = lstData
            };
            return Json(model, JsonRequestBehavior.AllowGet);



        }
        public JsonResult ShowDetails(int?id) {

            JsonArray result = new JsonArray();



            var details = db.OrderDetails.Where(b=>b.OrderHeaderID == id).FirstOrDefault();

            result.param1 = db.Employees.Where(a => a.EmployeeID == details.OrderHeaders.EmployeeID).Select(b => b.LastName + ", " + b.FirstName).FirstOrDefault();
                            
            result.param2 = details.MealDetails.Name;
            result.param3 = details.MealDetails.MealType;
            
          
            result.status = "success";
            return Json(result);

        }
        public JsonResult VoidMeal(VoidMeal item)
        {

            JsonArray res = new JsonArray();

            
            try
            {
                int cnt = db.OrderDetails.Where(a => a.OrderHeaders.ID == item.OrderHeaderID).Where(a => a.Status == "Served").Count();
                if (cnt > 0)
                {
                    res.message = "Cannot delete. Some items related to this item has already been served.";
                    res.status = "failed";
                }
                else
                {
                    OrderHeader det = db.OrderHeaders.Find(item.OrderHeaderID);
                    if (det.Status != "Active")
                    {
                        res.message = "Item already been " + det.Status;
                        res.status = "failed";
                    }
                    else
                    {
                        det.Status = "Cancelled";
                        db.Entry(det).State = EntityState.Modified;
                        db.SaveChanges();
                        db.VoidMeals.Add(item);
                        db.SaveChanges();
                        res.status = "success";
                    }
                    

                    




                }
            }
            catch (Exception e)
            {
                res.message = e.Message;
                res.status = "failed";
               
            }



            Log log = new Log();
            log.descriptions = "Cancel Order Header. Header ID:" + item.OrderHeaderID;
            log.otherinfo = res.status + " " + res.message;
            db.Logs.Add(log);
            db.SaveChanges();



            return Json(res);

        }
    }
}

SubsidizedDutyMeal/Views/MealSchedule/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<style>
    tfoot input {
        width: 100%;
        padding: 3px;
        box-sizing: border-box;
    }

    #tbl_filter {
        display: none;
    }
</style>


<div class="modal fade" id="myModal" lass="modal hide" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Meal Info - Edit</h5>

            </div>
            <div class="modal-body">
                <div class="alert alert-success" id="alertbox" style="display: none; font-size:14px;">
                    <strong>Success!</strong> Data posted.
                </div>

                <input type="text" value="" id="detailID" hidden />
                <div class="form-group">
                    <label for="recipient-name" class="col-form-label">Employee Name:</label>
                    <input type="text" class="form-control" name="EmpName" id="EmpName">
                </div>
                <div class="form-group">
                    <label for="recipient-type" class="col-form-label">Meal Type:</label>
                    <input type="text" class="form-control" name="MealType" id="MealType">
                </div>
                <div class="form-group">
                    <label for="message-text" class="col-form-label">Meal Name:</label>
                    <input type="text" class="form-control" name="MealName" id="MealName">
                </div>
                <div class="form-group">
                    <label for="message-text" class="col-form-label">Reason:</label>
                    <textarea class="form-control" name="Reason" id="Reason"></textarea>
                </div>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" onClick="window.location.reload()">Close</button>
                <button type="button" class="btn btn-primary" id="btnVoid">Void</button>
            </div>
        </div>
    </div>
</div>





<div class="card">

    <div class="card-body">
        <h4 class="card-title">Meal Schedule</h4>

        <div class="form-group">
            <label class="col-form-label">Date</label>
            <div>
                <input name="Date" value="@ViewBag.Date" readonly type="text" class="form-control form-control-md" id="datepicker" placeholder="" style="background-color:white;" />
            </div>
        </div>

        <table id="tbl" class="table table-striped table-bordered dataTable" style="width: 100%">
            <thead>
                <tr>
                    <th>Employee ID</th>
                    <th>EmployeeName</th>
                    <th>Status</th>

                    <th>Action</th>
                </tr>
                <tr>
                    <th>Employee ID</th>
                    <th>EmployeeName</th>
                    <th>Status</th>

                    <th>Action</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>Employee ID</th>
                    <th>EmployeeName</th>
                    <th>Status</th>

                    <th>Action</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

<script>
    $(function () {

        $("#datepicker").datepicker("setDate", new Date());
    });


    


    $('#tbl thead tr:eq(1) th').each(function () {
        var title = $(this).text();

        if (title == "Action" || title == "") {
            $(this).html('');
        } else {

            $(this).html('<input type="text" class="form-control form-control-md" placeholder="Search ' + title + '" />');
        }

    });

    var table = $('#tbl').DataTable({
        "processing": true,
        "serverSide": true,
        "info": true,
        "lengthMenu": [[50, 100, 150, -1], [50, 100, 150, "All"]],
        "ajax": {
            "url": "@Url.Action("getData", "MealSchedule")",
            "type": "POST",
            "data": function (d) {
                d.noCols = 3,
                    d.dt = $('#datepicker').val();
            }
        },
        "dom": "Bfrtip",

        "columns": [
                    {
                "data": "EmployeeID", "orderable": true
               
            },

            {
                "data": "EmployeeName"
                , "orderable": true

            },
            {
                "data": "Status"
                , "orderable": true

            },

            {
                "data": "ID"
                , "orderable": false
                , "width": "10px"
                , "render": function (data, type, row, meta) {

                    //var $newLinkTarget = '<a href="javascript:deleteItemdetail(' + value + ')"><i class="menu-icon mdi mdi-delete"></i></a>';
                    var $newLinkTarget = '<button type="button" class="btn btn-inverse-danger btn-fw" data-id=' + row['ID'] + ' onclick="modalHere(this);">Void Order</button>';

                    return $newLinkTarget;
                }, "visible": true
            }



        ],
        "order": [[0, "asc"]]
            , "orderCellsTop": true
    });




            $(window).resize(function () {
                table.fnDraw(false)
            });

            // Apply the search
            var delay = (function () {
                var timer = 0;
                return function (callback, ms) {
                    clearTimeout(timer);
                    timer = setTimeout(callback, ms);
                };
            })();

            $('#tbl input').on('keyup change', function (e) {
                var keyCode = e.keyCode
                if (keyCode >= 9 && keyCode <= 27) {

                } else {
                    searchFunction(this);
                }
            });
            function searchFunction(e) {
                delay(function () {

                    table.column($(e).parent().index() + ':visible')
                    .search(e.value)
                    .draw();
                }, 1000);
    }
        function modalHere(v) {

            var $buttonClicked = $(v);
            var id = parseInt($buttonClicked.attr('data-id'))||0;
            $('#detailID').val(id);


                    $.ajax({
                        url: "@Url.Action("ShowDetails")"
                            , method: "POST"
                            , dataType: 'json'
                            , data: { id: id}
                            , success: function (responsedata) {
             
                                if (responsedata.status == "success") {
                                    $("#EmpName").val(responsedata.param1);
                                    $("#MealName").val(responsedata.param2);
                                    $("#MealType").val(responsedata.param3);

                                } else {
                                swal("Error deleting!", "Please try again", "error");
                                }

                            }
                    });

            $('#myModal').modal('show');
        }
    function deleteItemdetail(id) {
            swal({
            title: "Are you sure?",
            text: "Once void, you will not be able to recover this file!",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        }).then((willDelete) => {
            if (willDelete) {
                 $.post("@Url.Action("VoidOrder", "MealSchedule")", {id:id}
                       , function (responseData) {
                           if (responseData.status == "success") {
                               swal("Done!", "It was succesfully voided!", {
                                   icon: "success",
                               });
                               table.DataTable().ajax.reload();
                           } else {
                               swal("Error deleting!", "Please try again", "error");
                           }
                       });
            } else {
               swal("Transaction cancelled!");
            }
            });






    }


    $('#datepicker').datepicker().on('changeDate', function (ev) {
        table.ajax.reload();
    })
    $('#btnVoid').click(function () {
        var str = $('#Reason').val();
        if (str.trim() == "") {
            $('#Reason').focus();
            swal("Error voiding!", "Please fill out Reason", "error");
            return false;
        }

        
        $.ajax({
            url: "@Url.Action("VoidMeal")"
                , method: "POST"
                , dataType: 'json'
            , data: {
                OrderHeaderID: $('#detailID').val()
                , Reason: $('#Reason').val()
            }
                , success: function (responsedata) {
             
                    if (responsedata.status == "success") {
                        $("#alertbox")[0].style.display = "block";
                        table.ajax.reload();
                    } else {
                        swal("Error voiding!", responsedata.message, "error");
                    }

                }
        });
        

    })

</script>